export const FETCH_POSTS = 'FETCH_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const SET_POST_TO_DELETE = 'SET_POST_TO_DELETE';
export const DELETE_POST = 'DELETE_POST';
export const EMPTY_STATE_PROPS = 'EMPTY_STATE_PROPS';